services:
  - type: web
    name: nodejs-project
    env: node
    plan: free # or use a paid plan if needed
    buildCommand: 'npm install'
    startCommand: 'npm start'
    repo: https://github.com/STAR-KING0/LIEBE # Replace with your GitHub repository URL
    branch: main # or the branch you want to deploy
    autoDeploy: true # Automatically deploy new commits
    healthCheckPath: '/' # Adjust if your app has a health check path

  - type: cron
    name: restart-nodejs-project
    env: node
    plan: free
    schedule: '*/20 * * * *' # Every 20 minutes
    command: |
      curl -X POST -H "Authorization: Bearer $RENDER_API_TOKEN" \
      "https://api.render.com/v1/services/https://liebe-k2ob.onrender.com/deploys" # Replace with your service ID
